# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

ZSH_THEME="bauricio"

plugins=(git bundler rvm)

source $ZSH/oh-my-zsh.sh

export PATH=/usr/local/share:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin::/Users/mauricio/.rvm/bin
